package com.oracle.maket.model.javaben;

import java.io.Serializable;

/**
 * 购物车 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Carts implements Serializable {

	@Override
	public String toString() {
		return "Carts [cartid=" + cartid + ", goodsid=" + goodsid
				+ ", cartgoodsnumber=" + cartgoodsnumber + ", userid=" + userid
				+ "]";
	}

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** cartID. */
	private Integer cartid;

	/** 商品编号. */
	private Integer goodsid;

	/** 购物车内商品数量. */
	private Integer cartgoodsnumber;

	/** 用户编号. */
	private Integer userid;

	/**
	 * 僐儞僗僩儔僋僞.
	 */
	public Carts() {
	}

	/**
	 * cartID 傪愝掕偟傑偡.
	 * 
	 * @param cartid
	 *            cartID
	 */
	public void setCartid(Integer cartid) {
		this.cartid = cartid;
	}

	/**
	 * cartID 傪庢摼偟傑偡.
	 * 
	 * @return cartID
	 */
	public Integer getCartid() {
		return this.cartid;
	}

	/**
	 * 商品编号 傪愝掕偟傑偡.
	 * 
	 * @param goodsid
	 *            商品编号
	 */
	public void setGoodsid(Integer goodsid) {
		this.goodsid = goodsid;
	}

	/**
	 * 商品编号 傪庢摼偟傑偡.
	 * 
	 * @return 商品编号
	 */
	public Integer getGoodsid() {
		return this.goodsid;
	}

	/**
	 * 购物车内商品数量 傪愝掕偟傑偡.
	 * 
	 * @param cartgoodsnumber
	 *            购物车内商品数量
	 */
	public void setCartgoodsnumber(Integer cartgoodsnumber) {
		this.cartgoodsnumber = cartgoodsnumber;
	}

	/**
	 * 购物车内商品数量 傪庢摼偟傑偡.
	 * 
	 * @return 购物车内商品数量
	 */
	public Integer getCartgoodsnumber() {
		return this.cartgoodsnumber;
	}

	/**
	 * 用户编号 傪愝掕偟傑偡.
	 * 
	 * @param userid
	 *            用户编号
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * 用户编号 傪庢摼偟傑偡.
	 * 
	 * @return 用户编号
	 */
	public Integer getUserid() {
		return this.userid;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cartid == null) ? 0 : cartid.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Carts other = (Carts) obj;
		if (cartid == null) {
			if (other.cartid != null) {
				return false;
			}
		} else if (!cartid.equals(other.cartid)) {
			return false;
		}

		return true;
	}

}
