package com.oracle.maket.model.javaben;

import java.io.Serializable;

/**
 * 收藏夹 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Favorites implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 收藏夹编号. */
	private Integer favoriteid;

	/** 加入时间. */
	private String jointime;

	/** 分类名称. */
	private String distributename;

	/** 商品编号. */
	private Integer goodsid;

	/**
	 * 僐儞僗僩儔僋僞.
	 */
	public Favorites() {
	}

	/**
	 * 收藏夹编号 傪愝掕偟傑偡.
	 * 
	 * @param favoriteid
	 *            收藏夹编号
	 */
	public void setFavoriteid(Integer favoriteid) {
		this.favoriteid = favoriteid;
	}

	/**
	 * 收藏夹编号 傪庢摼偟傑偡.
	 * 
	 * @return 收藏夹编号
	 */
	public Integer getFavoriteid() {
		return this.favoriteid;
	}

	/**
	 * 加入时间 傪愝掕偟傑偡.
	 * 
	 * @param jointime
	 *            加入时间
	 */
	public void setJointime(String jointime) {
		this.jointime = jointime;
	}

	/**
	 * 加入时间 傪庢摼偟傑偡.
	 * 
	 * @return 加入时间
	 */
	public String getJointime() {
		return this.jointime;
	}

	/**
	 * 分类名称 傪愝掕偟傑偡.
	 * 
	 * @param distributename
	 *            分类名称
	 */
	public void setDistributename(String distributename) {
		this.distributename = distributename;
	}

	/**
	 * 分类名称 傪庢摼偟傑偡.
	 * 
	 * @return 分类名称
	 */
	public String getDistributename() {
		return this.distributename;
	}

	/**
	 * 商品编号 傪愝掕偟傑偡.
	 * 
	 * @param goodsid
	 *            商品编号
	 */
	public void setGoodsid(Integer goodsid) {
		this.goodsid = goodsid;
	}

	/**
	 * 商品编号 傪庢摼偟傑偡.
	 * 
	 * @return 商品编号
	 */
	public Integer getGoodsid() {
		return this.goodsid;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((favoriteid == null) ? 0 : favoriteid.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Favorites other = (Favorites) obj;
		if (favoriteid == null) {
			if (other.favoriteid != null) {
				return false;
			}
		} else if (!favoriteid.equals(other.favoriteid)) {
			return false;
		}

		return true;
	}

}
