package com.oracle.maket.model.javaben;

import java.io.Serializable;
import java.sql.Blob;

/**
 * 商品表 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Goods implements Serializable {

	@Override
	public String toString() {
		return "Goods [goodsid=" + goodsid + ", goodsname=" + goodsname
				+ ", brandname=" + brandname + ", price=" + price
				+ ", goodsnumber=" + goodsnumber + ", goodspicture="
				+ goodspicture + "]";
	}

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 商品编号. */
	private Integer goodsid;

	/** 商品名称. */
	private String goodsname;

	/** 品牌名. */
	private String brandname;

	/** 商品价格. */
	private Float price;

	/** 商品数量. */
	private Integer goodsnumber;

	/** 商品图片. */
	private String goodspicture;

	public String getGoodspicture() {
		return goodspicture;
	}

	public void setGoodspicture(String goodspicture) {
		this.goodspicture = goodspicture;
	}

	/**
	 * 僐儞僗僩儔僋僞.
	 */
	public Goods() {
	}

	/**
	 * 商品编号 傪愝掕偟傑偡.
	 * 
	 * @param goodsid
	 *            商品编号
	 */
	public void setGoodsid(Integer goodsid) {
		this.goodsid = goodsid;
	}

	/**
	 * 商品编号 傪庢摼偟傑偡.
	 * 
	 * @return 商品编号
	 */
	public Integer getGoodsid() {
		return this.goodsid;
	}

	/**
	 * 商品名称 傪愝掕偟傑偡.
	 * 
	 * @param goodsname
	 *            商品名称
	 */
	public void setGoodsname(String goodsname) {
		this.goodsname = goodsname;
	}

	/**
	 * 商品名称 傪庢摼偟傑偡.
	 * 
	 * @return 商品名称
	 */
	public String getGoodsname() {
		return this.goodsname;
	}

	/**
	 * 品牌名 傪愝掕偟傑偡.
	 * 
	 * @param brandname
	 *            品牌名
	 */
	public void setBrandname(String brandname) {
		this.brandname = brandname;
	}

	/**
	 * 品牌名 傪庢摼偟傑偡.
	 * 
	 * @return 品牌名
	 */
	public String getBrandname() {
		return this.brandname;
	}

	/**
	 * 商品价格 傪愝掕偟傑偡.
	 * 
	 * @param price
	 *            商品价格
	 */
	public void setPrice(Float price) {
		this.price = price;
	}

	/**
	 * 商品价格 傪庢摼偟傑偡.
	 * 
	 * @return 商品价格
	 */
	public Float getPrice() {
		return this.price;
	}

	/**
	 * 商品数量 傪愝掕偟傑偡.
	 * 
	 * @param goodsnumber
	 *            商品数量
	 */
	public void setGoodsnumber(Integer goodsnumber) {
		this.goodsnumber = goodsnumber;
	}

	/**
	 * 商品数量 傪庢摼偟傑偡.
	 * 
	 * @return 商品数量
	 */
	public Integer getGoodsnumber() {
		return this.goodsnumber;
	}

	/**
	 * 商品图片 傪愝掕偟傑偡.
	 * 
	 * @param goodspicture
	 *            商品图片
	 */
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((goodsid == null) ? 0 : goodsid.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Goods other = (Goods) obj;
		if (goodsid == null) {
			if (other.goodsid != null) {
				return false;
			}
		} else if (!goodsid.equals(other.goodsid)) {
			return false;
		}

		return true;
	}

}
