package com.oracle.maket.model.javaben;

import java.io.Serializable;

/**
 * 订单表 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Orders implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 订单编号. */
	private Integer ordersid;

	/** 订单时间. */
	private String orderstime;

	/** 用户编号. */
	private Integer userid;

	/** 订单状态. */
	private String state;

	/** 收货地址. */
	private String location;

	/** 备注. */
	private String notice;

	/**
	 * 僐儞僗僩儔僋僞.
	 */
	public Orders() {
	}

	/**
	 * 订单编号 傪愝掕偟傑偡.
	 * 
	 * @param ordersid
	 *            订单编号
	 */
	public void setOrdersid(Integer ordersid) {
		this.ordersid = ordersid;
	}

	/**
	 * 订单编号 傪庢摼偟傑偡.
	 * 
	 * @return 订单编号
	 */
	public Integer getOrdersid() {
		return this.ordersid;
	}

	/**
	 * 订单时间 傪愝掕偟傑偡.
	 * 
	 * @param orderstime
	 *            订单时间
	 */
	public void setOrderstime(String orderstime) {
		this.orderstime = orderstime;
	}

	/**
	 * 订单时间 傪庢摼偟傑偡.
	 * 
	 * @return 订单时间
	 */
	public String getOrderstime() {
		return this.orderstime;
	}

	/**
	 * 用户编号 傪愝掕偟傑偡.
	 * 
	 * @param userid
	 *            用户编号
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * 用户编号 傪庢摼偟傑偡.
	 * 
	 * @return 用户编号
	 */
	public Integer getUserid() {
		return this.userid;
	}

	/**
	 * 订单状态 傪愝掕偟傑偡.
	 * 
	 * @param state
	 *            订单状态
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * 订单状态 傪庢摼偟傑偡.
	 * 
	 * @return 订单状态
	 */
	public String getState() {
		return this.state;
	}

	/**
	 * 收货地址 傪愝掕偟傑偡.
	 * 
	 * @param location
	 *            收货地址
	 */
	public void setLocation(String location) {
		this.location = location;
	}

	/**
	 * 收货地址 傪庢摼偟傑偡.
	 * 
	 * @return 收货地址
	 */
	public String getLocation() {
		return this.location;
	}

	/**
	 * 备注 傪愝掕偟傑偡.
	 * 
	 * @param notice
	 *            备注
	 */
	public void setNotice(String notice) {
		this.notice = notice;
	}

	/**
	 * 备注 傪庢摼偟傑偡.
	 * 
	 * @return 备注
	 */
	public String getNotice() {
		return this.notice;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((ordersid == null) ? 0 : ordersid.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Orders other = (Orders) obj;
		if (ordersid == null) {
			if (other.ordersid != null) {
				return false;
			}
		} else if (!ordersid.equals(other.ordersid)) {
			return false;
		}

		return true;
	}

}
