package com.oracle.maket.model.javaben;

import java.io.Serializable;
import java.sql.Blob;

/**
 * 用户表 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Users implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 用户编号. */
	private Integer userid;

	/** 用户名. */
	private String username;

	/** 昵称. */
	private String nickname;

	/** 用户密码. */
	private String password;

	/** 年龄. */
	private Integer age;

	/** 性别. */
	private Boolean sex;

	/** 头像. */
	private Blob headimage;

	/** 电话. */
	private String telephone;

	/**
	 * 僐儞僗僩儔僋僞.
	 */
	public Users() {
	}

	/**
	 * 用户编号 傪愝掕偟傑偡.
	 * 
	 * @param userid
	 *            用户编号
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * 用户编号 傪庢摼偟傑偡.
	 * 
	 * @return 用户编号
	 */
	public Integer getUserid() {
		return this.userid;
	}

	/**
	 * 用户名 傪愝掕偟傑偡.
	 * 
	 * @param username
	 *            用户名
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * 用户名 傪庢摼偟傑偡.
	 * 
	 * @return 用户名
	 */
	public String getUsername() {
		return this.username;
	}

	/**
	 * 昵称 傪愝掕偟傑偡.
	 * 
	 * @param nickname
	 *            昵称
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	/**
	 * 昵称 傪庢摼偟傑偡.
	 * 
	 * @return 昵称
	 */
	public String getNickname() {
		return this.nickname;
	}

	/**
	 * 用户密码 傪愝掕偟傑偡.
	 * 
	 * @param password
	 *            用户密码
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * 用户密码 傪庢摼偟傑偡.
	 * 
	 * @return 用户密码
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * 年龄 傪愝掕偟傑偡.
	 * 
	 * @param age
	 *            年龄
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * 年龄 傪庢摼偟傑偡.
	 * 
	 * @return 年龄
	 */
	public Integer getAge() {
		return this.age;
	}

	/**
	 * 性别 傪愝掕偟傑偡.
	 * 
	 * @param sex
	 *            性别
	 */
	public void setSex(Boolean sex) {
		this.sex = sex;
	}

	/**
	 * 性别 傪庢摼偟傑偡.
	 * 
	 * @return 性别
	 */
	public Boolean getSex() {
		return this.sex;
	}

	/**
	 * 头像 傪愝掕偟傑偡.
	 * 
	 * @param headimage
	 *            头像
	 */
	public void setHeadimage(Blob headimage) {
		this.headimage = headimage;
	}

	/**
	 * 头像 傪庢摼偟傑偡.
	 * 
	 * @return 头像
	 */
	public Blob getHeadimage() {
		return this.headimage;
	}

	/**
	 * 电话 傪愝掕偟傑偡.
	 * 
	 * @param telephone
	 *            电话
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	/**
	 * 电话 傪庢摼偟傑偡.
	 * 
	 * @return 电话
	 */
	public String getTelephone() {
		return this.telephone;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((userid == null) ? 0 : userid.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Users other = (Users) obj;
		if (userid == null) {
			if (other.userid != null) {
				return false;
			}
		} else if (!userid.equals(other.userid)) {
			return false;
		}

		return true;
	}

}
